/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Date;
import java.time.LocalDate;
import java.util.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class scheOrder extends javax.swing.JFrame {
    
    public scheOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox4 = new javax.swing.JComboBox();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        everyGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        foodCombo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        foodQuantity = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        dayRadio = new javax.swing.JRadioButton();
        weekRadio = new javax.swing.JRadioButton();
        createButton = new javax.swing.JButton();
        monCheck = new javax.swing.JCheckBox();
        tueCheck = new javax.swing.JCheckBox();
        wedCheck = new javax.swing.JCheckBox();
        thurCheck = new javax.swing.JCheckBox();
        friCheck = new javax.swing.JCheckBox();
        satCheck = new javax.swing.JCheckBox();
        sunCheck = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        durCombo = new javax.swing.JComboBox();
        timeCombo = new javax.swing.JComboBox();
        jtfUntil = new javax.swing.JTextField();

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Customer Scheduled Order delivery");

        jLabel2.setText("Date from :");

        jLabel3.setText("Time :");

        jLabel4.setText("Duration :");

        jLabel5.setText("Until :");

        foodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodComboActionPerformed(evt);
            }
        });

        jLabel8.setText("Food and beverage:");

        foodQuantity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel9.setText("Every");

        everyGroup.add(dayRadio);
        dayRadio.setSelected(true);
        dayRadio.setText("day");
        dayRadio.setToolTipText("");
        dayRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayRadioActionPerformed(evt);
            }
        });

        everyGroup.add(weekRadio);
        weekRadio.setText("week");
        weekRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weekRadioActionPerformed(evt);
            }
        });

        createButton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        createButton.setLabel("CREATE");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        monCheck.setEnabled(false);
        monCheck.setLabel("Monday");

        tueCheck.setEnabled(false);
        tueCheck.setLabel("Tuesday");

        wedCheck.setEnabled(false);
        wedCheck.setLabel("Wednesday");

        thurCheck.setEnabled(false);
        thurCheck.setLabel("Thursday");

        friCheck.setEnabled(false);
        friCheck.setLabel("Friday");
        friCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friCheckActionPerformed(evt);
            }
        });

        satCheck.setEnabled(false);
        satCheck.setLabel("Saturday");

        sunCheck.setEnabled(false);
        sunCheck.setLabel("Sunday");

        jLabel15.setText("Restaurant :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "James Fool", "Kim Gari", "Hello&Co" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        durCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 month", "3 months", "6 months", "1 year" }));
        durCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                durComboActionPerformed(evt);
            }
        });

        timeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Morning (8am)", "Afternoon (1pm)", "Evening (5pm)", "Night (7pm)" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(timeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfUntil, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(durCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weekRadio)
                                    .addComponent(thurCheck)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(wedCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sunCheck))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tueCheck)
                                            .addComponent(monCheck))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(friCheck)
                                            .addComponent(satCheck)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dayRadio)
                                        .addGap(158, 158, 158)
                                        .addComponent(jLabel8))))))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(foodCombo, 0, 160, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(foodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jtfUntil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(timeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(dayRadio)
                                    .addComponent(durCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(foodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(foodQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)))
                        .addComponent(weekRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(monCheck)
                            .addComponent(friCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tueCheck)
                            .addComponent(satCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wedCheck)
                            .addComponent(sunCheck))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(thurCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );

        getAccessibleContext().setAccessibleName("CREATE");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFromActionPerformed
            Calendar cl = Calendar.getInstance();
        SimpleDateFormat SDF = new SimpleDateFormat("dd/MM/yyyy");
        Date date = dateFrom.getDate();
        cl.setTime(date);
        int SelectedDur = durCombo.getSelectedIndex();
        switch (SelectedDur) {
            case 0: {
                cl.add(Calendar.MONTH, 1);
                break;
            }
            case 1: {
                cl.add(Calendar.MONTH, 3);
                break;
            }
            case 2: {
                cl.add(Calendar.MONTH, 6);
                break;
            }
            case 3: {
                cl.add(Calendar.YEAR, 1);
                break;
            }
        }
        String formated = SDF.format(cl.getTime());
        jtfUntil.setText(formated);
    }//GEN-LAST:event_dateFromActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        
        try {
            
            SimpleDateFormat SDF = new SimpleDateFormat("dd/MM/yyyy");
            Date date = dateFrom.getDate();
            String dateFro = SDF.format(date);
            String dateToo = jtfUntil.getText().toString();
            String time = timeCombo.getSelectedItem().toString();
            String rest = jComboBox2.getSelectedItem().toString();
            String foodie = foodCombo.getSelectedItem().toString();
            String quan = foodQuantity.getSelectedItem().toString();
            String day = dayRadio.getText();
            String dura = durCombo.getSelectedItem().toString();
            String week = "";
            String[] combineDay;
            
            if (monCheck.isSelected()) {
                week += monCheck.getText() + ",";
            }
            if (tueCheck.isSelected()) {
                week += tueCheck.getText() + ",";
            }
            if (wedCheck.isSelected()) {
                week += wedCheck.getText() + ",";
            }
            if (thurCheck.isSelected()) {
                week += thurCheck.getText() + ",";
            }
            if (friCheck.isSelected()) {
                week += friCheck.getText() + ",";
            }
            if (satCheck.isSelected()) {
                week += satCheck.getText() + ",";
            }
            if (sunCheck.isSelected()) {
                week += sunCheck.getText() + ",";
            }
            if (!week.equals("")) {
                week = week.substring(0, week.lastIndexOf(","));
            }
            if (dayRadio.isSelected()) {
                JOptionPane.showMessageDialog(null, "Scheduled order is from " + dateFro + " until "
                        + dateToo + "\n Scheduled order time is at " + time + " session\n Every " + day + " ordered " + quan +" "+ foodie + " from " + rest);
            } else if (weekRadio.isSelected()) {
                JOptionPane.showMessageDialog(null, "Scheduled order is from " + dateFro + " until "
                        + dateToo + "\n Scheduled order time is at " + time + " session\n Every " + week + " ordered " + quan +" "+ foodie + " from " + rest);
            }
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(rootPane, "Please complete all the field to complete the order.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        

    }//GEN-LAST:event_createButtonActionPerformed

    private void dayRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayRadioActionPerformed
        monCheck.setEnabled(false);
        tueCheck.setEnabled(false);
        wedCheck.setEnabled(false);
        thurCheck.setEnabled(false);
        friCheck.setEnabled(false);
        satCheck.setEnabled(false);
        sunCheck.setEnabled(false);
        
        monCheck.setSelected(false);
        tueCheck.setSelected(false);
        wedCheck.setSelected(false);
        thurCheck.setSelected(false);
        friCheck.setSelected(false);
        satCheck.setSelected(false);
        sunCheck.setSelected(false);

    }//GEN-LAST:event_dayRadioActionPerformed

    private void friCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friCheckActionPerformed

    private void foodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodComboActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String SelectedRestarurant = jComboBox2.getSelectedItem().toString();
        String SelectedFood = jComboBox2.getSelectedItem().toString();
        switch (SelectedRestarurant) {
            case ("James Fool"): {
                foodCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Chicken Chop set", "Black Pepper Chicken Chop set", "Mushroom Breakfast set", "Fish Fillet set", "Salad set"}));
                break;
            }
            case ("Kim Gari"): {
                foodCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"HK Breakfast set", "HK Lunch set", "HK Dinner set", "HK tea time set", "Cheesy Chicken Rice set"}));
                break;
            }
            case ("Hello&Co"): {
                foodCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Hawaii Chicken Pizza set", "English Cordon Bleu set", "Caesar Salad set", "Chocolate Cake set", "Sirloin Steak set"}));
                break;
            }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void weekRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weekRadioActionPerformed
        monCheck.setEnabled(true);
        tueCheck.setEnabled(true);
        wedCheck.setEnabled(true);
        thurCheck.setEnabled(true);
        friCheck.setEnabled(true);
        satCheck.setEnabled(true);
        sunCheck.setEnabled(true);
    }//GEN-LAST:event_weekRadioActionPerformed

    private void durComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_durComboActionPerformed
        Calendar cl = Calendar.getInstance();
        SimpleDateFormat SDF = new SimpleDateFormat("dd/MM/yyyy");
        Date date = dateFrom.getDate();
        cl.setTime(date);
        int SelectedDur = durCombo.getSelectedIndex();
        switch (SelectedDur) {
            case 0: {
                cl.add(Calendar.MONTH, 1);
                break;
            }
            case 1: {
                cl.add(Calendar.MONTH, 3);
                break;
            }
            case 2: {
                cl.add(Calendar.MONTH, 6);
                break;
            }
            case 3: {
                cl.add(Calendar.YEAR, 1);
                break;
            }
        }
        String formated = SDF.format(cl.getTime());
        jtfUntil.setText(formated);
    }//GEN-LAST:event_durComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scheOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JButton createButton;
    private javax.swing.JRadioButton dayRadio;
    private javax.swing.JComboBox durCombo;
    private javax.swing.ButtonGroup everyGroup;
    private javax.swing.JComboBox foodCombo;
    private javax.swing.JComboBox foodQuantity;
    private javax.swing.JCheckBox friCheck;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jtfUntil;
    private javax.swing.JCheckBox monCheck;
    private javax.swing.JCheckBox satCheck;
    private javax.swing.JCheckBox sunCheck;
    private javax.swing.JCheckBox thurCheck;
    private javax.swing.JComboBox timeCombo;
    private javax.swing.JCheckBox tueCheck;
    private javax.swing.JCheckBox wedCheck;
    private javax.swing.JRadioButton weekRadio;
    // End of variables declaration//GEN-END:variables
}
