
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Me
 */
public class Order extends javax.swing.JFrame {
    static DefaultTableModel model;
    static String total;
    
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jDialog1 = new javax.swing.JDialog();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        Button_Mineral = new javax.swing.JButton();
        Button_Soya = new javax.swing.JButton();
        Button_Sprite = new javax.swing.JButton();
        Button_Cry = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_List = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Button_DTB = new javax.swing.JButton();
        Button_TB = new javax.swing.JButton();
        Button_DMB = new javax.swing.JButton();
        Button_MB = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Button_IceC = new javax.swing.JButton();
        Button_ApplePie = new javax.swing.JButton();
        Button_BananaB = new javax.swing.JButton();
        Button_LemonY = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        Button_Eng = new javax.swing.JButton();
        Button_Australia = new javax.swing.JButton();
        Button_Italy = new javax.swing.JButton();
        Button_Hype = new javax.swing.JButton();
        jButton_Submit = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Label_TotalPrice = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Mebu_Submit = new javax.swing.JMenu();
        Menu_Reset = new javax.swing.JMenu();
        Menu_Exit = new javax.swing.JMenu();

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Beverage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        Button_Mineral.setText("Mineral Water");
        Button_Mineral.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_Mineral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_MineralMouseClicked(evt);
            }
        });

        Button_Soya.setText("Soya");
        Button_Soya.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_Soya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SoyaMouseClicked(evt);
            }
        });

        Button_Sprite.setText("Sprite");
        Button_Sprite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_SpriteMouseClicked(evt);
            }
        });

        Button_Cry.setText("Crysanthenum");
        Button_Cry.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_Cry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_CryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button_Mineral, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Button_Soya, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Cry, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Mineral, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Sprite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Soya, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Cry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Total(RM)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_List);
        if (jTable_List.getColumnModel().getColumnCount() > 0) {
            jTable_List.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTable_List.getColumnModel().getColumn(1).setPreferredWidth(5);
            jTable_List.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Burger", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        Button_DTB.setText("Double Teen Burger");
        Button_DTB.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_DTB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_DTBMouseClicked(evt);
            }
        });

        Button_TB.setText("Teen Burger");
        Button_TB.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_TBMouseClicked(evt);
            }
        });

        Button_DMB.setText("Double Mooza Burger");
        Button_DMB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_DMBMouseClicked(evt);
            }
        });

        Button_MB.setText("Mooza Burger");
        Button_MB.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_MB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_MBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Button_DTB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_DMB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Button_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_MB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_DTB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_DMB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_MB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dessert", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        Button_IceC.setText("Ice - Cream");
        Button_IceC.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_IceC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_IceCMouseClicked(evt);
            }
        });

        Button_ApplePie.setText("Apple Pie");
        Button_ApplePie.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_ApplePie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ApplePieMouseClicked(evt);
            }
        });

        Button_BananaB.setText("Banana Boat");
        Button_BananaB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_BananaBMouseClicked(evt);
            }
        });

        Button_LemonY.setText("Lemon Yogurt");
        Button_LemonY.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_LemonY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_LemonYMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Button_IceC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_BananaB, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Button_ApplePie, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_LemonY, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_IceC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_BananaB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_ApplePie, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_LemonY, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salad", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        Button_Eng.setText("England Salad");
        Button_Eng.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_Eng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_EngMouseClicked(evt);
            }
        });

        Button_Australia.setText("Australia Salad");
        Button_Australia.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_Australia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_AustraliaMouseClicked(evt);
            }
        });

        Button_Italy.setText("Italy Salad");
        Button_Italy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_ItalyMouseClicked(evt);
            }
        });

        Button_Hype.setText("Hype Salad");
        Button_Hype.setPreferredSize(new java.awt.Dimension(135, 23));
        Button_Hype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_HypeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(Button_Eng, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Italy, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(Button_Australia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Hype, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Eng, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Italy, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Australia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Hype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_Submit.setText("Submit");
        jButton_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SubmitActionPerformed(evt);
            }
        });

        jButton_Reset.setText("Cancel");
        jButton_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ResetMouseClicked(evt);
            }
        });
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total (RM) :");
        jLabel3.setToolTipText("");

        Label_TotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Label_TotalPrice.setText("0.00");

        Mebu_Submit.setText("Submit");
        jMenuBar1.add(Mebu_Submit);

        Menu_Reset.setText("Reset");
        Menu_Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_ResetMouseClicked(evt);
            }
        });
        jMenuBar1.add(Menu_Reset);

        Menu_Exit.setText("Exit");
        jMenuBar1.add(Menu_Exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_Submit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Reset))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label_TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Submit)
                    .addComponent(jButton_Reset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ResetMouseClicked
        DefaultTableModel models = (DefaultTableModel)this.jTable_List.getModel();
        jTable_List.clearSelection();
        models.setRowCount(0);
    }//GEN-LAST:event_jButton_ResetMouseClicked

    private void Button_DTBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_DTBMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Double Teen Burger") == true){
            Integer PackageIndex = CheckPackageIndex("Double Teen Burger");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 12.50;
            TotalPrice += 12.50;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Double Teen Burger");
            String PackageName = "Double Teen Burger";
            Integer PackageCount = 1;
            Double PackagePrice = 12.50;
            TotalPrice += 12.50;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_DTBMouseClicked

    private void Button_DMBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_DMBMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Double Mooza Burger") == true){
            Integer PackageIndex = CheckPackageIndex("Double Mooza Burger");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 15.50;
            TotalPrice += 15.50;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Double Mooza Burger");
            String PackageName = "Double Mooza Burger";
            Integer PackageCount = 1;
            Double PackagePrice = 15.50;
            TotalPrice += 15.50;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_DMBMouseClicked

    private void Button_TBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_TBMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Teen Burger") == true){
            Integer PackageIndex = CheckPackageIndex("Teen Burger");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 7.50;
            TotalPrice += 7.50;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Teen Burger");
            String PackageName = "Teen Burger";
            Integer PackageCount = 1;
            Double PackagePrice = 7.50;
            TotalPrice += 7.50;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_TBMouseClicked

    private void Button_MBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_MBMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Mooza Burger") == true){
            Integer PackageIndex = CheckPackageIndex("Mooza Burger");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 10.50;
            TotalPrice += 10.50;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Mooza Burger");
            String PackageName = "Mooza Burger";
            Integer PackageCount = 1;
            Double PackagePrice = 10.50;
            TotalPrice += 10.50;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_MBMouseClicked

    private void Button_IceCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_IceCMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Ice - Cream") == true){
            Integer PackageIndex = CheckPackageIndex("Ice - Cream");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 5.0;
            TotalPrice += 5.0;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Ice - Cream");
            String PackageName = "Ice - Cream";
            Integer PackageCount = 1;
            Double PackagePrice = 5.0;
            TotalPrice += 5.0;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_IceCMouseClicked

    private void Button_BananaBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_BananaBMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Banana Boat") == true){
            Integer PackageIndex = CheckPackageIndex("Banana Boat");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 7.0;
            TotalPrice += 7.0;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Banana Boat");
            String PackageName = "Banana Boat";
            Integer PackageCount = 1;
            Double PackagePrice = 7.0;
            TotalPrice += 7.0;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_BananaBMouseClicked

    private void Button_ApplePieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ApplePieMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Apple Pie") == true){
            Integer PackageIndex = CheckPackageIndex("Apple Pie");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 4.0;
            TotalPrice += 4.0;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Apple Pie");
            String PackageName = "Apple Pie";
            Integer PackageCount = 1;
            Double PackagePrice = 4.0;
            TotalPrice += 4.0;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_ApplePieMouseClicked

    private void Button_LemonYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_LemonYMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Lemon Yogurt") == true){
            Integer PackageIndex = CheckPackageIndex("Lemon Yogurt");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 6.0;
            TotalPrice += 6.0;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Lemon Yogurt");
            String PackageName = "Lemon Yogurt";
            Integer PackageCount = 1;
            Double PackagePrice = 6.0;
            TotalPrice += 6.0;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_LemonYMouseClicked

    private void Button_MineralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_MineralMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Mineral Water") == true){
            Integer PackageIndex = CheckPackageIndex("Mineral Water");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 2.0;
            TotalPrice += 2.0;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Mineral Water");
            String PackageName = "Mineral Water";
            Integer PackageCount = 1;
            Double PackagePrice = 2.0;
            TotalPrice += 2.0;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_MineralMouseClicked

    private void Button_SpriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SpriteMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Sprite") == true){
            Integer PackageIndex = CheckPackageIndex("Sprite");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 3.0;
            TotalPrice += 3.0;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Sprite");
            String PackageName = "Sprite";
            Integer PackageCount = 1;
            Double PackagePrice = 3.0;
            TotalPrice += 3.0;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_SpriteMouseClicked

    private void Button_SoyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_SoyaMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Soya") == true){
            Integer PackageIndex = CheckPackageIndex("Soya");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 2.5;
            TotalPrice += 2.5;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Soya");
            String PackageName = "Soya";
            Integer PackageCount = 1;
            Double PackagePrice = 2.5;
            TotalPrice += 2.5;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_SoyaMouseClicked

    private void Button_CryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_CryMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Crysanthenum") == true){
            Integer PackageIndex = CheckPackageIndex("Crysanthenum");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 2.5;
            TotalPrice += 2.5;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Crysanthenum");
            String PackageName = "Crysanthenum";
            Integer PackageCount = 1;
            Double PackagePrice = 2.5;
            TotalPrice += 2.5;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_CryMouseClicked

    private void Button_EngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_EngMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("England Salad") == true){
            Integer PackageIndex = CheckPackageIndex("England Salad");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 7.5;
            TotalPrice += 7.5;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("England Salad");
            String PackageName = "England Salad";
            Integer PackageCount = 1;
            Double PackagePrice = 7.5;
            TotalPrice += 7.5;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_EngMouseClicked

    private void Button_ItalyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_ItalyMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Italy Salad") == true){
            Integer PackageIndex = CheckPackageIndex("Italy Salad");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 8.5;
            TotalPrice += 8.5;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Italy Salad");
            String PackageName = "Italy Salad";
            Integer PackageCount = 1;
            Double PackagePrice = 8.5;
            TotalPrice += 8.5;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_ItalyMouseClicked

    private void Button_AustraliaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_AustraliaMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Australia Salad") == true){
            Integer PackageIndex = CheckPackageIndex("Australia Salad");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 8.5;
            TotalPrice += 8.5;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Australia Salad");
            String PackageName = "Australia Salad";
            Integer PackageCount = 1;
            Double PackagePrice = 8.5;
            TotalPrice += 8.5;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_AustraliaMouseClicked

    private void Button_HypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_HypeMouseClicked
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Double TotalPrice =Double.parseDouble(Label_TotalPrice.getText().trim());
        
        if(CheckPackageAvailable("Hype Salad") == true){
            Integer PackageIndex = CheckPackageIndex("Hype Salad");
            Integer PackageCount = (Integer) Model.getValueAt(PackageIndex,1);
            Double PackagePrice = (Double) Model.getValueAt(PackageIndex,2);
            
            PackageCount += 1;
            PackagePrice += 9.5;
            TotalPrice += 9.5;
            Model.setValueAt(PackageCount,PackageIndex,1);
            Model.setValueAt(PackagePrice,PackageIndex,2);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
        else{
            Integer PackageIndex = CheckPackageIndex("Hype Salad");
            String PackageName = "Hype Salad";
            Integer PackageCount = 1;
            Double PackagePrice = 9.5;
            TotalPrice += 9.5;
            Object[] row = {PackageName , PackageCount, PackagePrice };
            Model.addRow(row);
            Label_TotalPrice.setText(TotalPrice.toString());
        }
    }//GEN-LAST:event_Button_HypeMouseClicked

    private void Menu_ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_ResetMouseClicked
        DefaultTableModel model = (DefaultTableModel)this.jTable_List.getModel();
        jTable_List.clearSelection();
        model.setRowCount(0);
    }//GEN-LAST:event_Menu_ResetMouseClicked

    private void jButton_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SubmitActionPerformed
       model = (DefaultTableModel) jTable_List.getModel(); // TODO add your handling code here:
       this.setVisible(false);
       new AgileInterface1().setVisible(true);
       total = Label_TotalPrice.getText();
    }//GEN-LAST:event_jButton_SubmitActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
       int confirm =JOptionPane.showConfirmDialog(null, "Confirm?","Do you want to cancel your purchase?",JOptionPane.YES_NO_OPTION);
       if(confirm == JOptionPane.YES_OPTION){
           JOptionPane.showMessageDialog(null, "Thank you for your petronage");
           this.setVisible(false);
           
       }
    }//GEN-LAST:event_jButton_ResetActionPerformed
 
    private Boolean CheckPackageAvailable(String PPackage){
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Boolean Available = false;
            for (int count = 0; count < Model.getRowCount(); count++){
                if(Model.getValueAt(count, 0).toString().equals(PPackage)){
                    Available = true;   
                }
            }
        return Available;
     }
    
    private Integer CheckPackageIndex(String PPackage){
        DefaultTableModel Model = (DefaultTableModel)this.jTable_List.getModel();
        Integer PackgeIndex = 0;
            for (int count = 0; count < Model.getRowCount(); count++){
                if(Model.getValueAt(count, 0).toString().equals(PPackage)){
                    PackgeIndex = count;   
                }
            }
        return PackgeIndex;
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ApplePie;
    private javax.swing.JButton Button_Australia;
    private javax.swing.JButton Button_BananaB;
    private javax.swing.JButton Button_Cry;
    private javax.swing.JButton Button_DMB;
    private javax.swing.JButton Button_DTB;
    private javax.swing.JButton Button_Eng;
    private javax.swing.JButton Button_Hype;
    private javax.swing.JButton Button_IceC;
    private javax.swing.JButton Button_Italy;
    private javax.swing.JButton Button_LemonY;
    private javax.swing.JButton Button_MB;
    private javax.swing.JButton Button_Mineral;
    private javax.swing.JButton Button_Soya;
    private javax.swing.JButton Button_Sprite;
    private javax.swing.JButton Button_TB;
    private javax.swing.JLabel Label_TotalPrice;
    private javax.swing.JMenu Mebu_Submit;
    private javax.swing.JMenu Menu_Exit;
    private javax.swing.JMenu Menu_Reset;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_Submit;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable_List;
    // End of variables declaration//GEN-END:variables
}
